### ISSUE TITLE
Mac | WebDriver | DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by angryreid** [Frrrrrrrrank/auto_job__find__chatgpt__rpa#28]
(session not created: DevToolsActivePort file doesn't exist)
(The process started from chrome location /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:

**Comment by angryreid** [comment]
Mac OS BigSur V11.4
Python V3.11
Google Chrome V120.0.6099.216

**Comment by angryreid** [comment]
It's will be great appreciation with anyone's help, Thanks in advance.

**Comment by Frrrrrrrrank** [comment]
This seems to be a problem about the chrome driver. Since I don't have a Mac system computer, this problem may not be solved in the short term. I am asking my friends to try to solve it.
You can temporarily solve it as follows. First add the following code in function `def open_browser_with_options(url, browser):`，this function is in the finding_jobs.py：


    elif browser == "safari":
        driver = webdriver.Safari()


Then change browser_type = "chrome" to browser_type = "safari" in write_response.py.

As far as I know rpa requires no additional configuration when using safari. This may temporarily solve your problem.

**Comment by angryreid** [comment]
Thanks Frank，as of now i can see Safari can be opened, will close this issue.
